### ISSUE TITLE
Installing via NPM doesn't generate a binary

### ISSUE THREAD

**Issue by ryall** [netzmacht/assetic-autoprefixer#4]
I'm having a little trouble getting this to work. There's no binary generated from installing via NPM and setting the path to `/usr/local/lib/node_modules/autoprefixer/lib/autoprefixer.js` causes an empty CSS file to be generated.

**Comment by dmolineus** [comment]
The binary got removed since 6.0, see https://github.com/postcss/autoprefixer/releases?after=6.0.1
You have to install https://github.com/ai/autoprefixer-cli

**Comment by ryall** [comment]
Thanks very much.
